addpath( ...
	'\\janeway\User AG Bluhm\Cerfontaine\Software\Common\drawing\movie', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Gate Optimization\Common', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Bootstrap Tomography\Common', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Decoherence\Common', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Common', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Common\drawing', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Common\drawing\arrow', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Common\drawing\arrow3d', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Common\drawing\customplots', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Common\helper', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Common\scripts', ...
	  '\\janeway\User AG Bluhm\Cerfontaine\Software\Experiment\common', ...
	  '\\janeway\User AG Bluhm\Cerfontaine\Software\Experiment\pulsecontrol', ...
    '\\janeway\User AG Bluhm\Cerfontaine\Software\Experiment\bs', ...
    '\\janeway\User Ag Bluhm\Cerfontaine\Software\Process Tomography' ...
	);