addpath( ...
	'Y:\Cerfontaine\Software\Common\drawing\movie', ...
    'Y:\Cerfontaine\Software\Gate Optimization\Common', ...
    'Y:\Cerfontaine\Software\Bootstrap Tomography\Common', ...
    'Y:\Cerfontaine\Software\Decoherence\Common', ...
    'Y:\Cerfontaine\Software\Common', ...
    'Y:\Cerfontaine\Software\Common\drawing', ...
    'Y:\Cerfontaine\Software\Common\drawing\arrow', ...
    'Y:\Cerfontaine\Software\Common\drawing\arrow3d', ...
    'Y:\Cerfontaine\Software\Common\drawing\customplots', ...
    'Y:\Cerfontaine\Software\Common\helper', ...
    'Y:\Cerfontaine\Software\Common\scripts', ...
	  'Y:\Cerfontaine\Software\Experiment\common', ...
	  'Y:\Cerfontaine\Software\Experiment\pulsecontrol', ...
    'Y:\Cerfontaine\Software\Experiment\bs', ...
    'Y:\Cerfontaine\Software\Process Tomography' ...
	);