addpath( ...
     '\\tsclient\Y\Cerfontaine\Software\Gate Optimization\Common;', ...
     '\\tsclient\Y\Cerfontaine\Software\Bootstrap Tomography\Common;', ...
     '\\tsclient\Y\Cerfontaine\Software\Decoherence\Common;', ...
     '\\tsclient\Y\Cerfontaine\Software\Common;', ...
     '\\tsclient\Y\Cerfontaine\Software\Common\drawing;', ...
     '\\tsclient\Y\Cerfontaine\Software\Common\drawing\arrow;', ...
     '\\tsclient\Y\Cerfontaine\Software\Common\drawing\arrow3d;', ...
     '\\tsclient\Y\Cerfontaine\Software\Common\drawing\customplots;', ....
     '\\tsclient\Y\Cerfontaine\Software\Common\helper;', ...
     '\\tsclient\Y\Cerfontaine\Software\Common\scripts;' ...
	);